version: '3'
services:
  mysql:
    image: mariadb
    command: --max_allowed_packet=256M
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    ports:
       - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  litespeed:
    build: ./config/litespeed/${LITESPEED}/
    image: litespeedtech/openlitespeed-beta:latest
    env_file:
      - .env
    volumes:
        - ./conf:/usr/local/lsws/conf
        - ./bin/container:/usr/local/bin
        - ./sites:/var/www/vhosts/
        - ./logs:/usr/local/lsws/logs/
    ports:
      - 80:80
      - 443:443
      - 7080:7080
    environment:
      WEB_ADMIN_PASSWORD: ${WEB_ADMIN_PASSWORD}
    restart: always
  adminer:
    image: dockette/adminer:full
    ports:
      - 8080:80
    environment:
      - MEMORY=-1
